In [1]:
import pycaret
from pycaret.regression import *
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np
import sklearn

In [2]:
dataset = pd.read_csv('Datamatrix_gpd.csv')
data = dataset.sample(frac=0.9, random_state=786)
data_unseen = dataset.drop(data.index)

data.reset_index(drop=True, inplace=True)
data_unseen.reset_index(drop=True, inplace=True)

print('Data for Modeling: ' + str(data.shape))
print('Unseen Data For Predictions ' + str(data_unseen.shape))

Data for Modeling: (2161, 6)
Unseen Data For Predictions (240, 6)

In [3]:
exp_reg = setup(data = data, target = '20*20*D', session_id=123, ignore_features = ['MFR_transient'],
                  normalize = True,  
                  combine_rare_levels = True, rare_level_threshold = 0.05,
                  remove_multicollinearity = True, multicollinearity_threshold = 0.95, 
                  log_experiment = True, experiment_name = 'Bed Test')

In [4]:
top3 = compare_models(exclude = ['ransac'],fold=5, n_select = 3)

In [5]:
et = create_model('et')

## Blend

In [6]:
blender_top3 = blend_models(top3)

In [7]:
bagged_et = ensemble_model(et, fold = 10)

In [8]:
boosting_et = ensemble_model(et, method = 'Boosting')

In [9]:
stack_1 = stack_models(top3)

In [ ]:
dashboard(et)

Changing class type to RandomForestRegressionExplainer...
Generating self.shap_explainer = shap.TreeExplainer(model)
Building ExplainerDashboard..
Detected notebook environment, consider setting mode='external', mode='inline' or mode='jupyterlab' to keep the notebook interactive while the dashboard is running...
Warning: calculating shap interaction values can be slow! Pass shap_interaction=False to remove interactions tab.
Generating layout...
Calculating shap values...
Calculating predictions...
Calculating residuals...
Calculating absolute residuals...
Warning: mean-absolute-percentage-error is very large (192721447239.59506), you can hide it from the metrics by passing parameter show_metrics...
Calculating shap interaction values...
Reminder: TreeShap computational complexity is O(TLD^2), where T is the number of trees, L is the maximum number of leaves in any tree and D the maximal depth of any tree. So reducing these will speed up the calculation.
Warning: mean-absolute-percentage-error is very large (192721447239.59506), you can hide it from the metrics by passing parameter show_metrics...
Warning: mean-absolute-percentage-error is very large (192721447239.59506), you can hide it from the metrics by passing parameter show_metrics...
Calculating dependencies...
Calculating importances...
Calculating ShadowDecTree for each individual decision tree...
Reminder: you can store the explainer (including calculated dependencies) with explainer.dump('explainer.joblib') and reload with e.g. ClassifierExplainer.from_file('explainer.joblib')
Registering callbacks...
Starting ExplainerDashboard on http://10.0.0.5:8050
Dash is running on http://0.0.0.0:8050/

 * Serving Flask app 'explainerdashboard.dashboards' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off

 * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://10.0.0.5:8050/ (Press CTRL+C to quit)
10.0.0.5 - - [07/Apr/2022 21:55:36] "GET / HTTP/1.1" 200 -
10.0.0.5 - - [07/Apr/2022 21:55:36] "GET /assets/bootstrap.min.css?m=1649251105.633885 HTTP/1.1" 304 -
10.0.0.5 - - [07/Apr/2022 21:55:37] "GET /_dash-layout HTTP/1.1" 200 -
10.0.0.5 - - [07/Apr/2022 21:55:37] "GET /_dash-dependencies HTTP/1.1" 200 -
10.0.0.5 - - [07/Apr/2022 21:55:37] "GET /_dash-component-suites/dash/dcc/async-graph.js HTTP/1.1" 200 -
10.0.0.5 - - [07/Apr/2022 21:55:37] "GET /_dash-component-suites/dash/dcc/async-plotlyjs.js HTTP/1.1" 200 -
10.0.0.5 - - [07/Apr/2022 21:55:37] "POST /_dash-update-component HTTP/1.1" 204 -
10.0.0.5 - - [07/Apr/2022 21:55:37] "POST /_dash-update-component HTTP/1.1" 200 -
10.0.0.5 - - [07/Apr/2022 21:55:37] "POST /_dash-update-component HTTP/1.1" 200 -
10.0.0.5 - - [07/Apr/2022 21:55:37] "POST /_dash-update-component HTTP/1.1" 200 -
10.0.0.5 - - [07/Apr/2022 21:55:37] "POST /_dash-update-component HTTP/1.1" 200 -
10.0.0.5 - - [07/Apr/2022 21:55:37] "POST /_dash-update-component HTTP/1.1" 200 -
10.0.0.5 - - [07/Apr/2022 21:55:37] "POST /_dash-update-component HTTP/1.1" 200 -
10.0.0.5 - - [07/Apr/2022 21:55:37] "POST /_dash-update-component HTTP/1.1" 200 -
10.0.0.5 - - [07/Apr/2022 21:55:37] "POST /_dash-update-component HTTP/1.1" 200 -
10.0.0.5 - - [07/Apr/2022 21:55:37] "POST /_dash-update-component HTTP/1.1" 200 -
10.0.0.5 - - [07/Apr/2022 21:55:37] "POST /_dash-update-component HTTP/1.1" 200 -
10.0.0.5 - - [07/Apr/2022 21:55:37] "POST /_dash-update-component HTTP/1.1" 200 -
10.0.0.5 - - [07/Apr/2022 21:55:37] "POST /_dash-update-component HTTP/1.1" 200 -
10.0.0.5 - - [07/Apr/2022 21:55:37] "POST /_dash-update-component HTTP/1.1" 200 -
10.0.0.5 - - [07/Apr/2022 21:55:37] "POST /_dash-update-component HTTP/1.1" 200 -
10.0.0.5 - - [07/Apr/2022 21:55:37] "POST /_dash-update-component HTTP/1.1" 200 -
10.0.0.5 - - [07/Apr/2022 21:55:37] "POST /_dash-update-component HTTP/1.1" 200 -
10.0.0.5 - - [07/Apr/2022 21:55:37] "POST /_dash-update-component HTTP/1.1" 200 -
10.0.0.5 - - [07/Apr/2022 21:55:37] "POST /_dash-update-component HTTP/1.1" 200 -
10.0.0.5 - - [07/Apr/2022 21:55:37] "POST /_dash-update-component HTTP/1.1" 200 -
10.0.0.5 - - [07/Apr/2022 21:55:37] "POST /_dash-update-component HTTP/1.1" 200 -
10.0.0.5 - - [07/Apr/2022 21:55:37] "POST /_dash-update-component HTTP/1.1" 200 -
10.0.0.5 - - [07/Apr/2022 21:55:37] "POST /_dash-update-component HTTP/1.1" 200 -
10.0.0.5 - - [07/Apr/2022 21:55:37] "POST /_dash-update-component HTTP/1.1" 200 -
10.0.0.5 - - [07/Apr/2022 21:55:37] "POST /_dash-update-component HTTP/1.1" 200 -
10.0.0.5 - - [07/Apr/2022 21:55:37] "POST /_dash-update-component HTTP/1.1" 200 -
10.0.0.5 - - [07/Apr/2022 21:55:37] "POST /_dash-update-component HTTP/1.1" 200 -
10.0.0.5 - - [07/Apr/2022 21:55:37] "POST /_dash-update-component HTTP/1.1" 200 -
10.0.0.5 - - [07/Apr/2022 21:55:38] "POST /_dash-update-component HTTP/1.1" 200 -
10.0.0.5 - - [07/Apr/2022 21:55:38] "POST /_dash-update-component HTTP/1.1" 200 -
10.0.0.5 - - [07/Apr/2022 21:55:38] "POST /_dash-update-component HTTP/1.1" 200 -
10.0.0.5 - - [07/Apr/2022 21:55:38] "POST /_dash-update-component HTTP/1.1" 200 -
10.0.0.5 - - [07/Apr/2022 21:55:38] "POST /_dash-update-component HTTP/1.1" 200 -
10.0.0.5 - - [07/Apr/2022 21:55:38] "POST /_dash-update-component HTTP/1.1" 200 -
10.0.0.5 - - [07/Apr/2022 21:55:38] "POST /_dash-update-component HTTP/1.1" 204 -
10.0.0.5 - - [07/Apr/2022 21:55:38] "POST /_dash-update-component HTTP/1.1" 200 -
10.0.0.5 - - [07/Apr/2022 21:55:38] "POST /_dash-update-component HTTP/1.1" 204 -
10.0.0.5 - - [07/Apr/2022 21:55:38] "POST /_dash-update-component HTTP/1.1" 200 -
10.0.0.5 - - [07/Apr/2022 21:55:38] "POST /_dash-update-component HTTP/1.1" 204 -
10.0.0.5 - - [07/Apr/2022 21:55:38] "POST /_dash-update-component HTTP/1.1" 200 -
10.0.0.5 - - [07/Apr/2022 21:55:38] "POST /_dash-update-component HTTP/1.1" 200 -
10.0.0.5 - - [07/Apr/2022 21:55:38] "POST /_dash-update-component HTTP/1.1" 200 -
10.0.0.5 - - [07/Apr/2022 21:55:38] "POST /_dash-update-component HTTP/1.1" 200 -
10.0.0.5 - - [07/Apr/2022 21:55:38] "POST /_dash-update-component HTTP/1.1" 200 -
10.0.0.5 - - [07/Apr/2022 21:55:38] "POST /_dash-update-component HTTP/1.1" 200 -
10.0.0.5 - - [07/Apr/2022 21:55:38] "POST /_dash-update-component HTTP/1.1" 200 -
10.0.0.5 - - [07/Apr/2022 21:55:38] "POST /_dash-update-component HTTP/1.1" 200 -
10.0.0.5 - - [07/Apr/2022 21:55:38] "POST /_dash-update-component HTTP/1.1" 200 -
10.0.0.5 - - [07/Apr/2022 21:55:38] "POST /_dash-update-component HTTP/1.1" 200 -
10.0.0.5 - - [07/Apr/2022 21:55:38] "POST /_dash-update-component HTTP/1.1" 204 -
10.0.0.5 - - [07/Apr/2022 21:55:38] "POST /_dash-update-component HTTP/1.1" 200 -
10.0.0.5 - - [07/Apr/2022 21:55:38] "POST /_dash-update-component HTTP/1.1" 200 -
10.0.0.5 - - [07/Apr/2022 21:55:38] "POST /_dash-update-component HTTP/1.1" 204 -
10.0.0.5 - - [07/Apr/2022 21:55:38] "POST /_dash-update-component HTTP/1.1" 200 -
10.0.0.5 - - [07/Apr/2022 21:55:38] "POST /_dash-update-component HTTP/1.1" 200 -
10.0.0.5 - - [07/Apr/2022 21:55:38] "POST /_dash-update-component HTTP/1.1" 200 -
10.0.0.5 - - [07/Apr/2022 21:55:38] "POST /_dash-update-component HTTP/1.1" 200 -
10.0.0.5 - - [07/Apr/2022 21:55:38] "POST /_dash-update-component HTTP/1.1" 200 -
10.0.0.5 - - [07/Apr/2022 21:55:38] "POST /_dash-update-component HTTP/1.1" 200 -
10.0.0.5 - - [07/Apr/2022 21:55:38] "POST /_dash-update-component HTTP/1.1" 200 -
10.0.0.5 - - [07/Apr/2022 21:55:38] "POST /_dash-update-component HTTP/1.1" 200 -
10.0.0.5 - - [07/Apr/2022 21:55:38] "POST /_dash-update-component HTTP/1.1" 200 -
10.0.0.5 - - [07/Apr/2022 21:55:38] "POST /_dash-update-component HTTP/1.1" 200 -
10.0.0.5 - - [07/Apr/2022 21:55:38] "POST /_dash-update-component HTTP/1.1" 200 -
10.0.0.5 - - [07/Apr/2022 21:55:38] "POST /_dash-update-component HTTP/1.1" 200 -
10.0.0.5 - - [07/Apr/2022 21:55:38] "POST /_dash-update-component HTTP/1.1" 204 -
10.0.0.5 - - [07/Apr/2022 21:55:38] "POST /_dash-update-component HTTP/1.1" 200 -
10.0.0.5 - - [07/Apr/2022 21:55:38] "POST /_dash-update-component HTTP/1.1" 200 -
10.0.0.5 - - [07/Apr/2022 21:55:38] "POST /_dash-update-component HTTP/1.1" 200 -
10.0.0.5 - - [07/Apr/2022 21:55:39] "POST /_dash-update-component HTTP/1.1" 200 -
10.0.0.5 - - [07/Apr/2022 21:55:39] "POST /_dash-update-component HTTP/1.1" 200 -
10.0.0.5 - - [07/Apr/2022 21:55:39] "POST /_dash-update-component HTTP/1.1" 200 -
10.0.0.5 - - [07/Apr/2022 21:55:39] "POST /_dash-update-component HTTP/1.1" 200 -
10.0.0.5 - - [07/Apr/2022 21:55:39] "POST /_dash-update-component HTTP/1.1" 200 -