In [1]:
import pycaret
from pycaret.regression import *
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np
import sklearn

In [2]:
dataset = pd.read_csv('Datamatrix_gpd.csv')
data = dataset.sample(frac=0.9, random_state=786)
data_unseen = dataset.drop(data.index)

data.reset_index(drop=True, inplace=True)
data_unseen.reset_index(drop=True, inplace=True)

print('Data for Modeling: ' + str(data.shape))
print('Unseen Data For Predictions ' + str(data_unseen.shape))

Data for Modeling: (2161, 6)
Unseen Data For Predictions (240, 6)

In [3]:
exp_reg = setup(data = data, target = '20*20*D', session_id=123, ignore_features = ['MFR_transient','Friction coefficient F', 'Spreading speed/m*s^(-1)'],
                  normalize = True,  
                  combine_rare_levels = True, rare_level_threshold = 0.05,
                  remove_multicollinearity = True, multicollinearity_threshold = 0.95, 
                  log_experiment = True, experiment_name = 'Bed Test')

In [4]:
top3 = compare_models(exclude = ['ransac'],fold=5, n_select = 3)

In [5]:
et = create_model('et')

## Blend

In [6]:
blender_top3 = blend_models(top3)

In [7]:
bagged_et = ensemble_model(et, fold = 10)

In [8]:
boosting_et = ensemble_model(et, method = 'Boosting')

In [9]:
stack_1 = stack_models(top3)

In [10]:
evaluate_model(et)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Hyperparameters', 'param…